In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

/home/jmliikan/.local/lib/python3.10/site-packages/pandas/core/arrays/masked.py:62: UserWarning: Pandas requires version '1.3.4' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

## Area codes with å, ä, ö to population data

In [153]:
population_df = pd.read_csv('../data/population_df.csv')

# Join municipality, code and name to form area code, add prefix 0
population_df['Area no-dots'] = '0' + population_df['municipality'].astype(str) + " " + population_df['code'].astype(str) + " " + population_df['name']

# Get original area names with letters å, ä, ö:
# Fetch district data
districts = pd.read_csv('../data/Helsinki_districts.csv')
districts = districts[districts['BASIC'] != 0]
districts = districts[['Helsinki statistical area code', 'Helsinki statistical area code 2']]
# Change 091 801 Ostersundomin peruspiiri to 091 801 ostersundomin peruspiiri
districts['Helsinki statistical area code 2'] = districts['Helsinki statistical area code 2'].str.replace('091 801 Ostersundomin peruspiiri', '091 801 ostersundomin peruspiiri') 

# Merge district names with letters å, ä, ö to population_df
population_df = pd.merge(left=population_df, right=districts, how='left', left_on='Area no-dots', right_on='Helsinki statistical area code 2')
population_df = population_df.drop('Helsinki statistical area code 2', axis=1)
population_df['Helsinki statistical area code'] = population_df['Helsinki statistical area code'].fillna(population_df['Area no-dots'])
population_df = population_df.rename(columns={'Helsinki statistical area code': 'Area'})

population_df.tail(20)

,Gender,Education % 15-24 years Second degree and special vocational training degree,Education % 15-24 years Lowest higher and lower university level,Education % 15-24 years Higher university degree and research training,Education % 15-24 years All levels of education,Education % 15-24 years Elementary or unknown,Education % 15-24 years Total graduates,Education % 25-44 years Second degree and special vocational training degree,Education % 25-44 years Lowest higher and lower university level,Education % 25-44 years Higher university degree and research training,...,Married couple and children,Unmarried couple without children,Unmarried couple and children,Father and children,Mother and children,municipality,code,name,Area no-dots,Area
348,0,0.042404,0.002298,0.000000,0.128936,0.084234,0.044702,0.129970,0.057688,0.053781,...,0.280322,0.156284,0.078051,0.022353,0.142909,91,701,Vartiokylan peruspiiri,091 701 Vartiokylan peruspiiri,091 701 Vartiokylän peruspiiri
349,1,0.043717,0.004144,0.000311,0.117062,0.068890,0.048172,0.094789,0.075831,0.074381,...,0.280322,0.156284,0.078051,0.022353,0.142909,91,701,Vartiokylan peruspiiri,091 701 Vartiokylan peruspiiri,091 701 Vartiokylän peruspiiri
350,0,0.041322,0.002558,0.000000,0.120622,0.076741,0.043880,0.146989,0.064345,0.061196,...,0.270795,0.156648,0.089253,0.029144,0.155738,91,702,Myllypuron peruspiiri,091 702 Myllypuron peruspiiri,091 702 Myllypuron peruspiiri
351,1,0.038050,0.003080,0.000000,0.103280,0.062149,0.041131,0.112158,0.077188,0.078094,...,0.270795,0.156648,0.089253,0.029144,0.155738,91,702,Myllypuron peruspiiri,091 702 Myllypuron peruspiiri,091 702 Myllypuron peruspiiri
352,0,0.044475,0.002073,0.000126,0.134682,0.088008,0.046674,0.152836,0.047239,0.030718,...,0.267876,0.142059,0.069184,0.026682,0.192470,91,703,Mellunkylan peruspiiri,091 703 Mellunkylan peruspiiri,091 703 Mellunkylän peruspiiri
353,1,0.047075,0.003674,0.000230,0.127619,0.076640,0.050979,0.127906,0.058614,0.036856,...,0.267876,0.142059,0.069184,0.026682,0.192470,91,703,Mellunkylan peruspiiri,091 703 Mellunkylan peruspiiri,091 703 Mellunkylän peruspiiri
354,0,0.041348,0.001876,0.000134,0.129272,0.085913,0.043359,0.134700,0.057566,0.047782,...,0.253005,0.150288,0.072114,0.024644,0.178265,91,704,Vuosaaren peruspiiri,091 704 Vuosaaren peruspiiri,091 704 Vuosaaren peruspiiri
355,1,0.039584,0.003713,0.000114,0.110641,0.067230,0.043411,0.107386,0.072657,0.058377,...,0.253005,0.150288,0.072114,0.024644,0.178265,91,704,Vuosaaren peruspiiri,091 704 Vuosaaren peruspiiri,091 704 Vuosaaren peruspiiri
356,0,0.050352,0.008560,0.000504,0.116818,0.057402,0.059416,0.105740,0.079557,0.108761,...,0.226776,0.230191,0.053962,0.023224,0.102459,91,80,Katajanokka,091 80 Katajanokka,091 80 Katajanokka
357,1,0.054640,0.007806,0.000434,0.109714,0.046834,0.062879,0.062446,0.088899,0.122290,...,0.226776,0.230191,0.053962,0.023224,0.102459,91,80,Katajanokka,091 80 Katajanokka,091 80 Katajanokka
358,0,0.072519,0.000000,0.000000,0.189567,0.117048,0.072519,0.055980,0.043257,0.030534,...,0.402214,0.097786,0.073801,0.042435,0.059041,91,801,ostersundomin peruspiiri,091 801 ostersundomin peruspiiri,091 801 Östersundomin peruspiiri
359,1,0.049731,0.002688,0.000000,0.165323,0.112903,0.052419,0.063172,0.049731,0.055108,...,0.402214,0.097786,0.073801,0.042435,0.059041,91,801,ostersundomin peruspiiri,091 801 ostersundomin peruspiiri,091 801 Östersundomin peruspiiri
360,0,0.050000,0.000000,0.000000,0.120000,0.070000,0.050000,0.055000,0.030000,0.075000,...,0.244444,0.111111,0.044444,0.014815,0.081481,91,90,Kaivopuisto,091 90 Kaivopuisto,091 90 Kaivopuisto
361,1,0.042453,0.009434,0.000000,0.108491,0.056604,0.051887,0.051887,0.033019,0.099057,...,0.244444,0.111111,0.044444,0.014815,0.081481,91,90,Kaivopuisto,091 90 Kaivopuisto,091 90 Kaivopuisto
362,0,0.045941,0.003424,0.000199,0.124748,0.075183,0.049565,0.139202,0.079563,0.082987,...,0.275851,0.172889,0.083733,0.022858,0.145590,91,997,Esikaupungit,091 997 Esikaupungit,091 997 Esikaupungit
363,1,0.046091,0.006647,0.000399,0.113049,0.059912,0.053136,0.101443,0.095361,0.100946,...,0.275851,0.172889,0.083733,0.022858,0.145590,91,997,Esikaupungit,091 997 Esikaupungit,091 997 Esikaupungit
364,0,0.068623,0.009455,0.000423,0.122246,0.043744,0.078502,0.148989,0.112253,0.144381,...,0.202834,0.311098,0.077402,0.018974,0.104751,91,998,Kantakaupunki,091 998 Kantakaupunki,091 998 Kantakaupunki
365,1,0.088223,0.017459,0.001057,0.147080,0.040342,0.106738,0.100800,0.129216,0.164055,...,0.202834,0.311098,0.077402,0.018974,0.104751,91,998,Kantakaupunki,091 998 Kantakaupunki,091 998 Kantakaupunki
366,0,0.039430,0.002767,0.000000,0.142225,0.100028,0.042197,0.148727,0.036386,0.039568,...,NaN,NaN,NaN,NaN,NaN,91,999,Muut,091 999 Muut,091 999 Muut
367,1,0.086763,0.011123,0.000000,0.212681,0.114794,0.097887,0.113459,0.066741,0.084538,...,NaN,NaN,NaN,NaN,NaN,91,999,Muut,091 999 Muut,091 999 Muut

In [155]:
# Save to file population_df2.csv
population_df.to_csv('../data/population_df2.csv', index=False)

## Data for one-person households

In [156]:
# Fetch data from file in folder 'data'
ones = pd.read_csv('../data/Helsinki_oneperson_households.csv')
ones

,"One-person hh, Gender","One-person hh, All ages","One-person hh, Age -19","One-person hh, Age 20-29","One-person hh, Age 30-39","One-person hh, Age 40-49","One-person hh, Age 50-59","One-person hh, Age 60-64","One-person hh, Age 65-69","One-person hh, Age 70-74","One-person hh, Age 75-79","One-person hh, Age 80-84","One-person hh, Age 85","One-person hh, Major district","One-person hh, District"
0,Men,1306,18,293,248,210.0,195,80,67,76,53,43,23,1 Eteläinen suurpiiri,101 Vironniemi
1,Women,1925,31,428,230,161.0,213,106,159,174,168,135,120,1 Eteläinen suurpiiri,101 Vironniemi
2,Men,3117,28,847,647,517.0,427,191,132,109,84,70,65,1 Eteläinen suurpiiri,102 Ullanlinna
3,Women,4575,92,1254,759,379.0,481,278,298,314,310,210,200,1 Eteläinen suurpiiri,102 Ullanlinna
4,Men,5299,77,1598,1238,795.0,661,278,178,162,162,69,81,1 Eteläinen suurpiiri,103 Kampinmalmi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,Women,5505,86,623,421,358.0,856,594,571,562,519,452,463,7 Itäinen suurpiiri,703 Mellunkylä
64,Men,3968,38,592,754,617.0,797,348,254,188,159,113,108,7 Itäinen suurpiiri,704 Vuosaari
65,Women,5606,49,556,439,426.0,986,544,557,617,518,467,447,7 Itäinen suurpiiri,704 Vuosaari
66,Men,68,1,2,7,11.0,16,7,6,5,7,3,3,8 Östersundomin suurpiiri,801 Östersundom
67,Women,45,0,2,2,6.0,10,5,3,4,4,5,4,8 Östersundomin suurpiiri,801 Östersundom

In [196]:
# Get data for total population per gender per district

# Fetch data of all population per district
allpeople = pd.read_csv('../data/Helsingin_vaesto_sukupuolen_ian_ja_aidinkielen_ruotsinkieliset_mukaan.csv',
                       encoding='ISO-8859-1')

# Remove rows that include total data for both genders ('Molemmat sukupuolet')
allpeople = allpeople[allpeople['Sukupuoli'] != 'Molemmat sukupuolet']
# Keep only needed columns
allpeople = allpeople[['Alue', 'Sukupuoli', 'Väestö yhteensä 2022']]
# Replace missing population information '..' with NaN
allpeople['Väestö yhteensä 2022'] = allpeople['Väestö yhteensä 2022'].replace('..', np.nan)


# Fetch district data and convert to same format as in one-person household data
distr = pd.read_csv('../data/Helsinki_districts.csv')
distr = distr[distr['BASIC'] != 0]

distr[['City code', 'District code', 'District level name']] = distr['Helsinki statistical area code'].str.split(' ', n=2, expand=True)
distr['District'] = distr['District code'] + " " + distr['Name']
distr = distr[['Helsinki statistical area code', 'District']]


# Join district code & name with allpeople
people = pd.merge(left=allpeople, right=distr, how='inner', left_on='Alue', right_on='Helsinki statistical area code')
people = people[['Sukupuoli', 'Väestö yhteensä 2022', 'District', 'Alue']]
people.columns = ['Gender', 'Population', 'District', 'District long code']
people['Gender'] = people['Gender'].replace({'Miehet': 'Men', 'Naiset': 'Women'})

people.head(50)

   Gender Population            District               District long code
0     Men       6064      101 Vironniemi   091 101 Vironniemen peruspiiri
1   Women       6920      101 Vironniemi   091 101 Vironniemen peruspiiri
2     Men       3355      10 Kruununhaka               091 10 Kruununhaka
3   Women       3867      10 Kruununhaka               091 10 Kruununhaka
4     Men        351           20 Kluuvi                    091 20 Kluuvi
5   Women        315           20 Kluuvi                    091 20 Kluuvi
6     Men       2358      80 Katajanokka               091 80 Katajanokka
7   Women       2738      80 Katajanokka               091 80 Katajanokka
8     Men      11283      102 Ullanlinna   091 102 Ullanlinnan peruspiiri
9   Women      13091      102 Ullanlinna   091 102 Ullanlinnan peruspiiri
10    Men        524  30 Kaartinkaupunki           091 30 Kaartinkaupunki
11  Women        515  30 Kaartinkaupunki           091 30 Kaartinkaupunki
12    Men       4308        50 Punavuori                 091 50 Punavuori
13  Women       4950        50 Punavuori                 091 50 Punavuori
14    Men        502             60 Eira                      091 60 Eira
15  Women        548             60 Eira                      091 60 Eira
16    Men       4859       70 Ullanlinna                091 70 Ullanlinna
17  Women       5915       70 Ullanlinna                091 70 Ullanlinna
18    Men        217      90 Kaivopuisto               091 90 Kaivopuisto
19  Women        220      90 Kaivopuisto               091 90 Kaivopuisto
20    Men        564      204 Hernesaari               091 204 Hernesaari
21  Women        588      204 Hernesaari               091 204 Hernesaari
22    Men        309     520 Suomenlinna              091 520 Suomenlinna
23  Women        355     520 Suomenlinna              091 520 Suomenlinna
24    Men        NaN     531 Länsisaaret              091 531 Länsisaaret
25  Women        NaN     531 Länsisaaret              091 531 Länsisaaret
26    Men      21160     103 Kampinmalmi  091 103 Kampinmalmin peruspiiri
27  Women      23273     103 Kampinmalmi  091 103 Kampinmalmin peruspiiri
28    Men       5811           40 Kamppi                    091 40 Kamppi
29  Women       6287           40 Kamppi                    091 40 Kamppi
30    Men       6840       130 Etu-Töölö                091 130 Etu-Töölö
31  Women       7888       130 Etu-Töölö                091 130 Etu-Töölö
32    Men       1368      201 Ruoholahti               091 201 Ruoholahti
33  Women       1495      201 Ruoholahti               091 201 Ruoholahti
34    Men        NaN      202 Lapinlahti               091 202 Lapinlahti
35  Women        NaN      202 Lapinlahti               091 202 Lapinlahti
36    Men       7130      203 Jätkäsaari               091 203 Jätkäsaari
37  Women       7588      203 Jätkäsaari               091 203 Jätkäsaari
38    Men       6911      104 Taka-Töölö   091 104 Taka-Töölön peruspiiri
39  Women       8432      104 Taka-Töölö   091 104 Taka-Töölön peruspiiri
40    Men       6911      140 Taka-Töölö               091 140 Taka-Töölö
41  Women       8432      140 Taka-Töölö               091 140 Taka-Töölö
42    Men      11563     105 Lauttasaari  091 105 Lauttasaaren peruspiiri
43  Women      13180     105 Lauttasaari  091 105 Lauttasaaren peruspiiri
44    Men       3836      311 Kotkavuori               091 311 Kotkavuori
45  Women       4508      311 Kotkavuori               091 311 Kotkavuori
46    Men       4126      312 Vattuniemi               091 312 Vattuniemi
47  Women       4689      312 Vattuniemi               091 312 Vattuniemi
48    Men       3601     313 Myllykallio              091 313 Myllykallio
49  Women       3983     313 Myllykallio              091 313 Myllykallio

In [203]:
# Join total population data with one-person household data
ones2 = pd.merge(left=ones, right=people, how='inner', left_on=['One-person hh, District', 'One-person hh, Gender'], right_on=['District', 'Gender'])
ones2 = ones2.drop(['One-person hh, District', 'One-person hh, Gender', 'One-person hh, Major district'], axis=1)
ones2['Population'] = ones2['Population'].apply(pd.to_numeric)
ones2

,"One-person hh, All ages","One-person hh, Age -19","One-person hh, Age 20-29","One-person hh, Age 30-39","One-person hh, Age 40-49","One-person hh, Age 50-59","One-person hh, Age 60-64","One-person hh, Age 65-69","One-person hh, Age 70-74","One-person hh, Age 75-79","One-person hh, Age 80-84","One-person hh, Age 85",Gender,Population,District,District long code
0,1306,18,293,248,210.0,195,80,67,76,53,43,23,Men,6064,101 Vironniemi,091 101 Vironniemen peruspiiri
1,1925,31,428,230,161.0,213,106,159,174,168,135,120,Women,6920,101 Vironniemi,091 101 Vironniemen peruspiiri
2,3117,28,847,647,517.0,427,191,132,109,84,70,65,Men,11283,102 Ullanlinna,091 102 Ullanlinnan peruspiiri
3,4575,92,1254,759,379.0,481,278,298,314,310,210,200,Women,13091,102 Ullanlinna,091 102 Ullanlinnan peruspiiri
4,5299,77,1598,1238,795.0,661,278,178,162,162,69,81,Men,21160,103 Kampinmalmi,091 103 Kampinmalmin peruspiiri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,5505,86,623,421,358.0,856,594,571,562,519,452,463,Women,20436,703 Mellunkylä,091 703 Mellunkylän peruspiiri
64,3968,38,592,754,617.0,797,348,254,188,159,113,108,Men,18248,704 Vuosaari,091 704 Vuosaaren peruspiiri
65,5606,49,556,439,426.0,986,544,557,617,518,467,447,Women,20542,704 Vuosaari,091 704 Vuosaaren peruspiiri
66,68,1,2,7,11.0,16,7,6,5,7,3,3,Men,908,801 Östersundom,091 801 Östersundomin peruspiiri
67,45,0,2,2,6.0,10,5,3,4,4,5,4,Women,877,801 Östersundom,091 801 Östersundomin peruspiiri

In [252]:
# Change the age specific columns from amounts to portions of total population

ones_portions = ones2.copy()

# Divide amounts of people in each one-person hh column by total population in district
# and add suffix '%'' to column names to indicate portions
cols_include = ones_portions.columns[~ones_portions.columns.isin(['Gender', 'Population', 'District', 'District long code'])]
for col in cols_include:
    ones_portions[col] = ones2[col].div(ones2['Population'], axis=0)
    ones_portions.rename(columns={col: col+', %'}, inplace=True)

# Merge with sub-district-level population data
ones_portions = pd.merge(left=ones_portions, right=people, how='right', 
                         left_on=['District', 'Gender'], right_on=['District', 'Gender'])
ones_portions = ones_portions.drop(['Population_x', 'District'], axis=1)
ones_portions = ones_portions.rename(columns={'District long code_x': 'District',
                                              'District long code_y': 'Area',
                                              'Population_y' : 'Population'})

# Fill down district-level name
ones_portions['District'] = ones_portions['District'].ffill()


# Copy rows where population is missing
no_pop = ones_portions[ones_portions['Population'].isna()]

# Remove the rows from ones_portions 
ones_portions = ones_portions[~ones_portions['Population'].isna()]

# Sort rows based on District, Gender and All ages
ones_portions = ones_portions.sort_values(by = ['District', 'Gender', 'One-person hh, All ages, %'], ascending = [True, True, False])
 
# Fill down values in portions columns to sub-district level
ones_portions = ones_portions.ffill()

# Append no-population rows back to population data
ones_portions =  pd.concat([ones_portions, no_pop])

# remove columns District and Population
ones_portions = ones_portions.drop(['District', 'Population'], axis=1)


# Change gender to categorical type
ones_portions['Gender'] = ones_portions['Gender'].map({'Men':0, 'Women':1})
ones_portions['Gender'] = ones_portions['Gender'].astype('category') 


# Sort along index
ones_portions.sort_index(inplace=True)


ones_portions

,"One-person hh, All ages, %","One-person hh, Age -19, %","One-person hh, Age 20-29, %","One-person hh, Age 30-39, %","One-person hh, Age 40-49, %","One-person hh, Age 50-59, %","One-person hh, Age 60-64, %","One-person hh, Age 65-69, %","One-person hh, Age 70-74, %","One-person hh, Age 75-79, %","One-person hh, Age 80-84, %","One-person hh, Age 85, %",Gender,Area
0,0.215369,0.002968,0.048318,0.040897,0.034631,0.032157,0.013193,0.011049,0.012533,0.008740,0.007091,0.003793,0,091 101 Vironniemen peruspiiri
1,0.278179,0.004480,0.061850,0.033237,0.023266,0.030780,0.015318,0.022977,0.025145,0.024277,0.019509,0.017341,1,091 101 Vironniemen peruspiiri
2,0.215369,0.002968,0.048318,0.040897,0.034631,0.032157,0.013193,0.011049,0.012533,0.008740,0.007091,0.003793,0,091 10 Kruununhaka
3,0.278179,0.004480,0.061850,0.033237,0.023266,0.030780,0.015318,0.022977,0.025145,0.024277,0.019509,0.017341,1,091 10 Kruununhaka
4,0.215369,0.002968,0.048318,0.040897,0.034631,0.032157,0.013193,0.011049,0.012533,0.008740,0.007091,0.003793,0,091 20 Kluuvi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,0.051311,0.000000,0.002281,0.002281,0.006842,0.011403,0.005701,0.003421,0.004561,0.004561,0.005701,0.004561,1,091 580 Karhusaari
358,0.074890,0.001101,0.002203,0.007709,0.012115,0.017621,0.007709,0.006608,0.005507,0.007709,0.003304,0.003304,0,091 591 Landbo
359,0.051311,0.000000,0.002281,0.002281,0.006842,0.011403,0.005701,0.003421,0.004561,0.004561,0.005701,0.004561,1,091 591 Landbo
360,0.074890,0.001101,0.002203,0.007709,0.012115,0.017621,0.007709,0.006608,0.005507,0.007709,0.003304,0.003304,0,091 592 Puroniitty
361,0.051311,0.000000,0.002281,0.002281,0.006842,0.011403,0.005701,0.003421,0.004561,0.004561,0.005701,0.004561,1,091 592 Puroniitty

### Merge one-person housefolds with population dataframe

In [253]:
# Read population data (including district names with and without å, ä, ö)
population_df2 = pd.read_csv('../data/population_df2.csv')

# Change gender to categorical type
population_df2['Gender'] = population_df2['Gender'].astype('category') 

population_df2

,Gender,Education % 15-24 years Second degree and special vocational training degree,Education % 15-24 years Lowest higher and lower university level,Education % 15-24 years Higher university degree and research training,Education % 15-24 years All levels of education,Education % 15-24 years Elementary or unknown,Education % 15-24 years Total graduates,Education % 25-44 years Second degree and special vocational training degree,Education % 25-44 years Lowest higher and lower university level,Education % 25-44 years Higher university degree and research training,...,Married couple and children,Unmarried couple without children,Unmarried couple and children,Father and children,Mother and children,municipality,code,name,Area no-dots,Area
0,0,0.059870,0.008553,0.000342,0.116319,0.047554,0.068765,0.105371,0.083134,0.157030,...,0.231140,0.248261,0.064205,0.021402,0.092563,91,10,Kruununhaka,091 10 Kruununhaka,091 10 Kruununhaka
1,1,0.079023,0.016667,0.000575,0.145402,0.049138,0.096264,0.074138,0.103736,0.157471,...,0.231140,0.248261,0.064205,0.021402,0.092563,91,10,Kruununhaka,091 10 Kruununhaka,091 10 Kruununhaka
2,0,0.058338,0.007025,0.000000,0.100794,0.035431,0.065363,0.168601,0.136225,0.140195,...,0.129346,0.413074,0.055633,0.013908,0.067455,91,101,Vilhonvuori,091 101 Vilhonvuori,091 101 Vilhonvuori
3,1,0.088615,0.018624,0.001502,0.143286,0.034545,0.108741,0.123160,0.141484,0.147792,...,0.129346,0.413074,0.055633,0.013908,0.067455,91,101,Vilhonvuori,091 101 Vilhonvuori,091 101 Vilhonvuori
4,0,0.056744,0.008216,0.000382,0.115017,0.049675,0.065342,0.107375,0.081582,0.138135,...,0.227415,0.243374,0.058991,0.021659,0.094329,91,101,Vironniemen peruspiiri,091 101 Vironniemen peruspiiri,091 101 Vironniemen peruspiiri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,1,0.046091,0.006647,0.000399,0.113049,0.059912,0.053136,0.101443,0.095361,0.100946,...,0.275851,0.172889,0.083733,0.022858,0.145590,91,997,Esikaupungit,091 997 Esikaupungit,091 997 Esikaupungit
364,0,0.068623,0.009455,0.000423,0.122246,0.043744,0.078502,0.148989,0.112253,0.144381,...,0.202834,0.311098,0.077402,0.018974,0.104751,91,998,Kantakaupunki,091 998 Kantakaupunki,091 998 Kantakaupunki
365,1,0.088223,0.017459,0.001057,0.147080,0.040342,0.106738,0.100800,0.129216,0.164055,...,0.202834,0.311098,0.077402,0.018974,0.104751,91,998,Kantakaupunki,091 998 Kantakaupunki,091 998 Kantakaupunki
366,0,0.039430,0.002767,0.000000,0.142225,0.100028,0.042197,0.148727,0.036386,0.039568,...,NaN,NaN,NaN,NaN,NaN,91,999,Muut,091 999 Muut,091 999 Muut
367,1,0.086763,0.011123,0.000000,0.212681,0.114794,0.097887,0.113459,0.066741,0.084538,...,NaN,NaN,NaN,NaN,NaN,91,999,Muut,091 999 Muut,091 999 Muut

In [257]:
# Merge one-person households with population data
population_df3 = pd.merge(left=population_df2, right=ones_portions, how='left', on=['Gender', 'Area'])

population_df3

,Gender,Education % 15-24 years Second degree and special vocational training degree,Education % 15-24 years Lowest higher and lower university level,Education % 15-24 years Higher university degree and research training,Education % 15-24 years All levels of education,Education % 15-24 years Elementary or unknown,Education % 15-24 years Total graduates,Education % 25-44 years Second degree and special vocational training degree,Education % 25-44 years Lowest higher and lower university level,Education % 25-44 years Higher university degree and research training,...,"One-person hh, Age 20-29, %","One-person hh, Age 30-39, %","One-person hh, Age 40-49, %","One-person hh, Age 50-59, %","One-person hh, Age 60-64, %","One-person hh, Age 65-69, %","One-person hh, Age 70-74, %","One-person hh, Age 75-79, %","One-person hh, Age 80-84, %","One-person hh, Age 85, %"
0,0,0.059870,0.008553,0.000342,0.116319,0.047554,0.068765,0.105371,0.083134,0.157030,...,0.048318,0.040897,0.034631,0.032157,0.013193,0.011049,0.012533,0.008740,0.007091,0.003793
1,1,0.079023,0.016667,0.000575,0.145402,0.049138,0.096264,0.074138,0.103736,0.157471,...,0.061850,0.033237,0.023266,0.030780,0.015318,0.022977,0.025145,0.024277,0.019509,0.017341
2,0,0.058338,0.007025,0.000000,0.100794,0.035431,0.065363,0.168601,0.136225,0.140195,...,0.101963,0.105889,0.059488,0.046460,0.017609,0.015407,0.012552,0.008150,0.004640,0.003391
3,1,0.088615,0.018624,0.001502,0.143286,0.034545,0.108741,0.123160,0.141484,0.147792,...,0.138324,0.085028,0.036568,0.037846,0.020173,0.023286,0.024842,0.019840,0.014227,0.014227
4,0,0.056744,0.008216,0.000382,0.115017,0.049675,0.065342,0.107375,0.081582,0.138135,...,0.048318,0.040897,0.034631,0.032157,0.013193,0.011049,0.012533,0.008740,0.007091,0.003793
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,1,0.046091,0.006647,0.000399,0.113049,0.059912,0.053136,0.101443,0.095361,0.100946,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364,0,0.068623,0.009455,0.000423,0.122246,0.043744,0.078502,0.148989,0.112253,0.144381,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
365,1,0.088223,0.017459,0.001057,0.147080,0.040342,0.106738,0.100800,0.129216,0.164055,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
366,0,0.039430,0.002767,0.000000,0.142225,0.100028,0.042197,0.148727,0.036386,0.039568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
367,1,0.086763,0.011123,0.000000,0.212681,0.114794,0.097887,0.113459,0.066741,0.084538,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [258]:
# Save to file population_df3.csv
population_df3.to_csv('../data/population_df3.csv', index=False)

## Data for morbidity index

In [ ]:
# Latest published data is from 2021 but we will make an assumption that the indices are the same in 2022.
# Indices for the whole city is 100.