In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Area codes with å, ä, ö to population data

**Don't run this section (two cells below) if you are using data that already includes these!**

Also, check that the file to be read exists.

In [153]:
# population_df = pd.read_csv('../data/population_df.csv')

# # Join municipality, code and name to form area code, add prefix 0
# population_df['Area no-dots'] = '0' + population_df['municipality'].astype(str) + " " + population_df['code'].astype(str) + " " + population_df['name']

# # Get original area names with letters å, ä, ö:
# # Fetch district data
# districts = pd.read_csv('../data/Helsinki_districts.csv')
# districts = districts[districts['BASIC'] != 0]
# districts = districts[['Helsinki statistical area code', 'Helsinki statistical area code 2']]
# # Change 091 801 Ostersundomin peruspiiri to 091 801 ostersundomin peruspiiri
# districts['Helsinki statistical area code 2'] = districts['Helsinki statistical area code 2'].str.replace('091 801 Ostersundomin peruspiiri', '091 801 ostersundomin peruspiiri') 

# # Merge district names with letters å, ä, ö to population_df
# population_df = pd.merge(left=population_df, right=districts, how='left', left_on='Area no-dots', right_on='Helsinki statistical area code 2')
# population_df = population_df.drop('Helsinki statistical area code 2', axis=1)
# population_df['Helsinki statistical area code'] = population_df['Helsinki statistical area code'].fillna(population_df['Area no-dots'])
# population_df = population_df.rename(columns={'Helsinki statistical area code': 'Area'})

# population_df.tail(20)

,Gender,Education % 15-24 years Second degree and special vocational training degree,Education % 15-24 years Lowest higher and lower university level,Education % 15-24 years Higher university degree and research training,Education % 15-24 years All levels of education,Education % 15-24 years Elementary or unknown,Education % 15-24 years Total graduates,Education % 25-44 years Second degree and special vocational training degree,Education % 25-44 years Lowest higher and lower university level,Education % 25-44 years Higher university degree and research training,...,Married couple and children,Unmarried couple without children,Unmarried couple and children,Father and children,Mother and children,municipality,code,name,Area no-dots,Area
348,0,0.042404,0.002298,0.000000,0.128936,0.084234,0.044702,0.129970,0.057688,0.053781,...,0.280322,0.156284,0.078051,0.022353,0.142909,91,701,Vartiokylan peruspiiri,091 701 Vartiokylan peruspiiri,091 701 Vartiokylän peruspiiri
349,1,0.043717,0.004144,0.000311,0.117062,0.068890,0.048172,0.094789,0.075831,0.074381,...,0.280322,0.156284,0.078051,0.022353,0.142909,91,701,Vartiokylan peruspiiri,091 701 Vartiokylan peruspiiri,091 701 Vartiokylän peruspiiri
350,0,0.041322,0.002558,0.000000,0.120622,0.076741,0.043880,0.146989,0.064345,0.061196,...,0.270795,0.156648,0.089253,0.029144,0.155738,91,702,Myllypuron peruspiiri,091 702 Myllypuron peruspiiri,091 702 Myllypuron peruspiiri
351,1,0.038050,0.003080,0.000000,0.103280,0.062149,0.041131,0.112158,0.077188,0.078094,...,0.270795,0.156648,0.089253,0.029144,0.155738,91,702,Myllypuron peruspiiri,091 702 Myllypuron peruspiiri,091 702 Myllypuron peruspiiri
352,0,0.044475,0.002073,0.000126,0.134682,0.088008,0.046674,0.152836,0.047239,0.030718,...,0.267876,0.142059,0.069184,0.026682,0.192470,91,703,Mellunkylan peruspiiri,091 703 Mellunkylan peruspiiri,091 703 Mellunkylän peruspiiri
353,1,0.047075,0.003674,0.000230,0.127619,0.076640,0.050979,0.127906,0.058614,0.036856,...,0.267876,0.142059,0.069184,0.026682,0.192470,91,703,Mellunkylan peruspiiri,091 703 Mellunkylan peruspiiri,091 703 Mellunkylän peruspiiri
354,0,0.041348,0.001876,0.000134,0.129272,0.085913,0.043359,0.134700,0.057566,0.047782,...,0.253005,0.150288,0.072114,0.024644,0.178265,91,704,Vuosaaren peruspiiri,091 704 Vuosaaren peruspiiri,091 704 Vuosaaren peruspiiri
355,1,0.039584,0.003713,0.000114,0.110641,0.067230,0.043411,0.107386,0.072657,0.058377,...,0.253005,0.150288,0.072114,0.024644,0.178265,91,704,Vuosaaren peruspiiri,091 704 Vuosaaren peruspiiri,091 704 Vuosaaren peruspiiri
356,0,0.050352,0.008560,0.000504,0.116818,0.057402,0.059416,0.105740,0.079557,0.108761,...,0.226776,0.230191,0.053962,0.023224,0.102459,91,80,Katajanokka,091 80 Katajanokka,091 80 Katajanokka
357,1,0.054640,0.007806,0.000434,0.109714,0.046834,0.062879,0.062446,0.088899,0.122290,...,0.226776,0.230191,0.053962,0.023224,0.102459,91,80,Katajanokka,091 80 Katajanokka,091 80 Katajanokka
358,0,0.072519,0.000000,0.000000,0.189567,0.117048,0.072519,0.055980,0.043257,0.030534,...,0.402214,0.097786,0.073801,0.042435,0.059041,91,801,ostersundomin peruspiiri,091 801 ostersundomin peruspiiri,091 801 Östersundomin peruspiiri
359,1,0.049731,0.002688,0.000000,0.165323,0.112903,0.052419,0.063172,0.049731,0.055108,...,0.402214,0.097786,0.073801,0.042435,0.059041,91,801,ostersundomin peruspiiri,091 801 ostersundomin peruspiiri,091 801 Östersundomin peruspiiri
360,0,0.050000,0.000000,0.000000,0.120000,0.070000,0.050000,0.055000,0.030000,0.075000,...,0.244444,0.111111,0.044444,0.014815,0.081481,91,90,Kaivopuisto,091 90 Kaivopuisto,091 90 Kaivopuisto
361,1,0.042453,0.009434,0.000000,0.108491,0.056604,0.051887,0.051887,0.033019,0.099057,...,0.244444,0.111111,0.044444,0.014815,0.081481,91,90,Kaivopuisto,091 90 Kaivopuisto,091 90 Kaivopuisto
362,0,0.045941,0.003424,0.000199,0.124748,0.075183,0.049565,0.139202,0.079563,0.082987,...,0.275851,0.172889,0.083733,0.022858,0.145590,91,997,Esikaupungit,091 997 Esikaupungit,091 997 Esikaupungit
363,1,0.046091,0.006647,0.000399,0.113049,0.059912,0.053136,0.101443,0.095361,0.100946,...,0.275851,0.172889,0.083733,0.022858,0.145590,91,997,Esikaupungit,091 997 Esikaupungit,091 997 Esikaupungit
364,0,0.068623,0.009455,0.000423,0.122246,0.043744,0.078502,0.148989,0.112253,0.144381,...,0.202834,0.311098,0.077402,0.018974,0.104751,91,998,Kantakaupunki,091 998 Kantakaupunki,091 998 Kantakaupunki
365,1,0.088223,0.017459,0.001057,0.147080,0.040342,0.106738,0.100800,0.129216,0.164055,...,0.202834,0.311098,0.077402,0.018974,0.104751,91,998,Kantakaupunki,091 998 Kantakaupunki,091 998 Kantakaupunki
366,0,0.039430,0.002767,0.000000,0.142225,0.100028,0.042197,0.148727,0.036386,0.039568,...,NaN,NaN,NaN,NaN,NaN,91,999,Muut,091 999 Muut,091 999 Muut
367,1,0.086763,0.011123,0.000000,0.212681,0.114794,0.097887,0.113459,0.066741,0.084538,...,NaN,NaN,NaN,NaN,NaN,91,999,Muut,091 999 Muut,091 999 Muut

In [155]:
# # Save to file population_df2.csv
# population_df.to_csv('../data/population_df2.csv', index=False)

## Data for one-person households

In [5]:
# Fetch data from file in folder 'data'
ones = pd.read_csv('../data/Helsinki_oneperson_households.csv')
ones

,"One-person hh, Gender","One-person hh, All ages","One-person hh, Age -19","One-person hh, Age 20-29","One-person hh, Age 30-39","One-person hh, Age 40-49","One-person hh, Age 50-59","One-person hh, Age 60-64","One-person hh, Age 65-69","One-person hh, Age 70-74","One-person hh, Age 75-79","One-person hh, Age 80-84","One-person hh, Age 85","One-person hh, Major district","One-person hh, District"
0,Men,1306,18,293,248,210.0,195,80,67,76,53,43,23,1 Eteläinen suurpiiri,101 Vironniemi
1,Women,1925,31,428,230,161.0,213,106,159,174,168,135,120,1 Eteläinen suurpiiri,101 Vironniemi
2,Men,3117,28,847,647,517.0,427,191,132,109,84,70,65,1 Eteläinen suurpiiri,102 Ullanlinna
3,Women,4575,92,1254,759,379.0,481,278,298,314,310,210,200,1 Eteläinen suurpiiri,102 Ullanlinna
4,Men,5299,77,1598,1238,795.0,661,278,178,162,162,69,81,1 Eteläinen suurpiiri,103 Kampinmalmi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,Women,5505,86,623,421,358.0,856,594,571,562,519,452,463,7 Itäinen suurpiiri,703 Mellunkylä
64,Men,3968,38,592,754,617.0,797,348,254,188,159,113,108,7 Itäinen suurpiiri,704 Vuosaari
65,Women,5606,49,556,439,426.0,986,544,557,617,518,467,447,7 Itäinen suurpiiri,704 Vuosaari
66,Men,68,1,2,7,11.0,16,7,6,5,7,3,3,8 Östersundomin suurpiiri,801 Östersundom
67,Women,45,0,2,2,6.0,10,5,3,4,4,5,4,8 Östersundomin suurpiiri,801 Östersundom

In [6]:
# Get data for total population per gender per district

# Fetch data of all population per district
allpeople = pd.read_csv('../data/Helsingin_vaesto_sukupuolen_ian_ja_aidinkielen_ruotsinkieliset_mukaan.csv',
                       encoding='ISO-8859-1')

# Remove rows that include total data for both genders ('Molemmat sukupuolet')
allpeople = allpeople[allpeople['Sukupuoli'] != 'Molemmat sukupuolet']
# Keep only needed columns
allpeople = allpeople[['Alue', 'Sukupuoli', 'Väestö yhteensä 2022']]
# Replace missing population information '..' with NaN
allpeople['Väestö yhteensä 2022'] = allpeople['Väestö yhteensä 2022'].replace('..', np.nan)


# Fetch district data and convert to same format as in one-person household data
distr = pd.read_csv('../data/Helsinki_districts.csv')
distr = distr[distr['BASIC'] != 0]

distr[['City code', 'District code', 'District level name']] = distr['Helsinki statistical area code'].str.split(' ', n=2, expand=True)
distr['District'] = distr['District code'] + " " + distr['Name']
distr = distr[['Helsinki statistical area code', 'District']]


# Join district code & name with allpeople
people = pd.merge(left=allpeople, right=distr, how='inner', left_on='Alue', right_on='Helsinki statistical area code')
people = people[['Sukupuoli', 'Väestö yhteensä 2022', 'District', 'Alue']]
people.columns = ['Gender', 'Population', 'District', 'District long code']
people['Gender'] = people['Gender'].replace({'Miehet': 'Men', 'Naiset': 'Women'})

people.head(10)

  Gender Population        District              District long code
0    Men       6064  101 Vironniemi  091 101 Vironniemen peruspiiri
1  Women       6920  101 Vironniemi  091 101 Vironniemen peruspiiri
2    Men       3355  10 Kruununhaka              091 10 Kruununhaka
3  Women       3867  10 Kruununhaka              091 10 Kruununhaka
4    Men        351       20 Kluuvi                   091 20 Kluuvi
5  Women        315       20 Kluuvi                   091 20 Kluuvi
6    Men       2358  80 Katajanokka              091 80 Katajanokka
7  Women       2738  80 Katajanokka              091 80 Katajanokka
8    Men      11283  102 Ullanlinna  091 102 Ullanlinnan peruspiiri
9  Women      13091  102 Ullanlinna  091 102 Ullanlinnan peruspiiri

In [7]:
# Join total population data with one-person household data
ones2 = pd.merge(left=ones, right=people, how='inner', left_on=['One-person hh, District', 'One-person hh, Gender'], right_on=['District', 'Gender'])
ones2 = ones2.drop(['One-person hh, District', 'One-person hh, Gender', 'One-person hh, Major district'], axis=1)
ones2['Population'] = ones2['Population'].apply(pd.to_numeric)
ones2

,"One-person hh, All ages","One-person hh, Age -19","One-person hh, Age 20-29","One-person hh, Age 30-39","One-person hh, Age 40-49","One-person hh, Age 50-59","One-person hh, Age 60-64","One-person hh, Age 65-69","One-person hh, Age 70-74","One-person hh, Age 75-79","One-person hh, Age 80-84","One-person hh, Age 85",Gender,Population,District,District long code
0,1306,18,293,248,210.0,195,80,67,76,53,43,23,Men,6064,101 Vironniemi,091 101 Vironniemen peruspiiri
1,1925,31,428,230,161.0,213,106,159,174,168,135,120,Women,6920,101 Vironniemi,091 101 Vironniemen peruspiiri
2,3117,28,847,647,517.0,427,191,132,109,84,70,65,Men,11283,102 Ullanlinna,091 102 Ullanlinnan peruspiiri
3,4575,92,1254,759,379.0,481,278,298,314,310,210,200,Women,13091,102 Ullanlinna,091 102 Ullanlinnan peruspiiri
4,5299,77,1598,1238,795.0,661,278,178,162,162,69,81,Men,21160,103 Kampinmalmi,091 103 Kampinmalmin peruspiiri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,5505,86,623,421,358.0,856,594,571,562,519,452,463,Women,20436,703 Mellunkylä,091 703 Mellunkylän peruspiiri
64,3968,38,592,754,617.0,797,348,254,188,159,113,108,Men,18248,704 Vuosaari,091 704 Vuosaaren peruspiiri
65,5606,49,556,439,426.0,986,544,557,617,518,467,447,Women,20542,704 Vuosaari,091 704 Vuosaaren peruspiiri
66,68,1,2,7,11.0,16,7,6,5,7,3,3,Men,908,801 Östersundom,091 801 Östersundomin peruspiiri
67,45,0,2,2,6.0,10,5,3,4,4,5,4,Women,877,801 Östersundom,091 801 Östersundomin peruspiiri

In [8]:
# Change the age specific columns from amounts to portions of total population

ones_portions = ones2.copy()

# Divide amounts of people in each one-person hh column by total population in district
# and add suffix '%'' to column names to indicate portions
cols_include = ones_portions.columns[~ones_portions.columns.isin(['Gender', 'Population', 'District', 'District long code'])]
for col in cols_include:
    ones_portions[col] = ones2[col].div(ones2['Population'], axis=0)
    ones_portions.rename(columns={col: col+', %'}, inplace=True)

# Merge with sub-district-level population data
ones_portions = pd.merge(left=ones_portions, right=people, how='right', 
                         left_on=['District', 'Gender'], right_on=['District', 'Gender'])
ones_portions = ones_portions.drop(['Population_x', 'District'], axis=1)
ones_portions = ones_portions.rename(columns={'District long code_x': 'District',
                                              'District long code_y': 'Area',
                                              'Population_y' : 'Population'})

# Fill down district-level name
ones_portions['District'] = ones_portions['District'].ffill()


# Copy rows where population is missing
no_pop = ones_portions[ones_portions['Population'].isna()]

# Remove the rows from ones_portions 
ones_portions = ones_portions[~ones_portions['Population'].isna()]

# Sort rows based on District, Gender and All ages
ones_portions = ones_portions.sort_values(by = ['District', 'Gender', 'One-person hh, All ages, %'], ascending = [True, True, False])
 
# Fill down values in portions columns to sub-district level
ones_portions = ones_portions.ffill()

# Append no-population rows back to population data
ones_portions =  pd.concat([ones_portions, no_pop])

# remove columns District and Population
ones_portions = ones_portions.drop(['District', 'Population'], axis=1)


# Change gender to categorical type
ones_portions['Gender'] = ones_portions['Gender'].map({'Men':0, 'Women':1})
ones_portions['Gender'] = ones_portions['Gender'].astype('category') 


# Sort along index
ones_portions.sort_index(inplace=True)


ones_portions

,"One-person hh, All ages, %","One-person hh, Age -19, %","One-person hh, Age 20-29, %","One-person hh, Age 30-39, %","One-person hh, Age 40-49, %","One-person hh, Age 50-59, %","One-person hh, Age 60-64, %","One-person hh, Age 65-69, %","One-person hh, Age 70-74, %","One-person hh, Age 75-79, %","One-person hh, Age 80-84, %","One-person hh, Age 85, %",Gender,Area
0,0.215369,0.002968,0.048318,0.040897,0.034631,0.032157,0.013193,0.011049,0.012533,0.008740,0.007091,0.003793,0,091 101 Vironniemen peruspiiri
1,0.278179,0.004480,0.061850,0.033237,0.023266,0.030780,0.015318,0.022977,0.025145,0.024277,0.019509,0.017341,1,091 101 Vironniemen peruspiiri
2,0.215369,0.002968,0.048318,0.040897,0.034631,0.032157,0.013193,0.011049,0.012533,0.008740,0.007091,0.003793,0,091 10 Kruununhaka
3,0.278179,0.004480,0.061850,0.033237,0.023266,0.030780,0.015318,0.022977,0.025145,0.024277,0.019509,0.017341,1,091 10 Kruununhaka
4,0.215369,0.002968,0.048318,0.040897,0.034631,0.032157,0.013193,0.011049,0.012533,0.008740,0.007091,0.003793,0,091 20 Kluuvi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,0.051311,0.000000,0.002281,0.002281,0.006842,0.011403,0.005701,0.003421,0.004561,0.004561,0.005701,0.004561,1,091 580 Karhusaari
358,0.074890,0.001101,0.002203,0.007709,0.012115,0.017621,0.007709,0.006608,0.005507,0.007709,0.003304,0.003304,0,091 591 Landbo
359,0.051311,0.000000,0.002281,0.002281,0.006842,0.011403,0.005701,0.003421,0.004561,0.004561,0.005701,0.004561,1,091 591 Landbo
360,0.074890,0.001101,0.002203,0.007709,0.012115,0.017621,0.007709,0.006608,0.005507,0.007709,0.003304,0.003304,0,091 592 Puroniitty
361,0.051311,0.000000,0.002281,0.002281,0.006842,0.011403,0.005701,0.003421,0.004561,0.004561,0.005701,0.004561,1,091 592 Puroniitty

## Data for morbidity index

In [9]:
# Latest published data is from 2021 but we will make an assumption that the indices are the same in 2022.
# Indices for the whole city is 100. 

# Read data and drop unneeded columns
morb_fetch = pd.read_csv('../data/Helsinki_morbidity_index.csv')
morb_fetch = morb_fetch.drop(['Morbidity, Population', 'Morbidity, Major district'], axis=1)

morb_fetch.head()

,"Morbidity, District","Morbidity, Morbidity index","Morbidity, Mortality index","Morbidity, Disability pension index","Morbidity, Medicine reimbursement index","Morbidity, Chronic diseases index"
0,Vironniemi,67.586539,69.787493,47.104700,85.867423,76.318461
1,Ullanlinna,65.665101,73.060317,43.092436,80.842549,67.995023
2,Kampinmalmi,82.818148,74.817956,78.870986,94.765503,88.586840
3,Taka-Töölö,87.902482,95.685431,78.013245,90.008771,85.981219
4,Lauttasaari,70.974337,72.153629,51.920147,88.849234,76.159888

In [16]:

# Merge morbidity data with district codes 

# Fetch district data
distr = pd.read_csv('../data/Helsinki_districts.csv')
distr = distr[distr['BASIC'] != 0]
distr = distr[['Helsinki statistical area code', 'District']]

# Join districts and morbidity data
morb = pd.merge(left=distr, right=morb_fetch, how='left', left_on='District', right_on='Morbidity, District')

# Rename
morb = morb.rename(columns={'Helsinki statistical area code': 'Area'})
morb = morb.drop(['District', 'Morbidity, District'], axis=1)

morb.head(50)

,Area,"Morbidity, Morbidity index","Morbidity, Mortality index","Morbidity, Disability pension index","Morbidity, Medicine reimbursement index","Morbidity, Chronic diseases index"
0,091 101 Vironniemen peruspiiri,67.586539,69.787493,47.104700,85.867423,76.318461
1,091 10 Kruununhaka,67.586539,69.787493,47.104700,85.867423,76.318461
2,091 20 Kluuvi,67.586539,69.787493,47.104700,85.867423,76.318461
3,091 80 Katajanokka,67.586539,69.787493,47.104700,85.867423,76.318461
4,091 102 Ullanlinnan peruspiiri,65.665101,73.060317,43.092436,80.842549,67.995023
5,091 30 Kaartinkaupunki,65.665101,73.060317,43.092436,80.842549,67.995023
6,091 50 Punavuori,65.665101,73.060317,43.092436,80.842549,67.995023
7,091 60 Eira,65.665101,73.060317,43.092436,80.842549,67.995023
8,091 70 Ullanlinna,65.665101,73.060317,43.092436,80.842549,67.995023
9,091 90 Kaivopuisto,65.665101,73.060317,43.092436,80.842549,67.995023
10,091 204 Hernesaari,65.665101,73.060317,43.092436,80.842549,67.995023
11,091 520 Suomenlinna,65.665101,73.060317,43.092436,80.842549,67.995023
12,091 531 Länsisaaret,65.665101,73.060317,43.092436,80.842549,67.995023
13,091 103 Kampinmalmin peruspiiri,82.818148,74.817956,78.870986,94.765503,88.586840
14,091 40 Kamppi,82.818148,74.817956,78.870986,94.765503,88.586840
15,091 130 Etu-Töölö,82.818148,74.817956,78.870986,94.765503,88.586840
16,091 201 Ruoholahti,82.818148,74.817956,78.870986,94.765503,88.586840
17,091 202 Lapinlahti,82.818148,74.817956,78.870986,94.765503,88.586840
18,091 203 Jätkäsaari,82.818148,74.817956,78.870986,94.765503,88.586840
19,091 104 Taka-Töölön peruspiiri,87.902482,95.685431,78.013245,90.008771,85.981219
20,091 140 Taka-Töölö,87.902482,95.685431,78.013245,90.008771,85.981219
21,091 105 Lauttasaaren peruspiiri,70.974337,72.153629,51.920147,88.849234,76.159888
22,091 311 Kotkavuori,70.974337,72.153629,51.920147,88.849234,76.159888
23,091 312 Vattuniemi,70.974337,72.153629,51.920147,88.849234,76.159888
24,091 313 Myllykallio,70.974337,72.153629,51.920147,88.849234,76.159888
25,091 314 Koivusaari,70.974337,72.153629,51.920147,88.849234,76.159888
26,091 201 Reijolan peruspiiri,100.060517,87.922642,110.102059,102.156851,100.630765
27,091 150 Meilahti,100.060517,87.922642,110.102059,102.156851,100.630765
28,091 161 Vanha Ruskeasuo,100.060517,87.922642,110.102059,102.156851,100.630765
29,091 162 Pikku Huopalahti,100.060517,87.922642,110.102059,102.156851,100.630765
30,091 180 Laakso,100.060517,87.922642,110.102059,102.156851,100.630765
31,091 202 Munkkiniemen peruspiiri,85.070119,78.960570,82.743505,93.506284,90.378942
32,091 301 Vanha Munkkiniemi,85.070119,78.960570,82.743505,93.506284,90.378942
33,091 302 Kuusisaari,85.070119,78.960570,82.743505,93.506284,90.378942
34,091 303 Lehtisaari,85.070119,78.960570,82.743505,93.506284,90.378942
35,091 304 Munkkivuori,85.070119,78.960570,82.743505,93.506284,90.378942
36,091 305 Niemenmäki,85.070119,78.960570,82.743505,93.506284,90.378942
37,091 306 Talinranta,85.070119,78.960570,82.743505,93.506284,90.378942
38,091 203 Haagan peruspiiri,104.312980,111.773187,101.344437,99.821315,102.880702
39,091 291 Etelä-Haaga,104.312980,111.773187,101.344437,99.821315,102.880702
40,091 292 Kivihaka,104.312980,111.773187,101.344437,99.821315,102.880702
41,091 293 Pohjois-Haaga,104.312980,111.773187,101.344437,99.821315,102.880702
42,091 294 Lassila,104.312980,111.773187,101.344437,99.821315,102.880702
43,091 204 Pitäjänmäen peruspiiri,100.216510,92.222125,112.076408,96.350997,103.612896
44,091 320 Konala,100.216510,92.222125,112.076408,96.350997,103.612896
45,091 461 Pajamäki,100.216510,92.222125,112.076408,96.350997,103.612896
46,091 462 Tali,100.216510,92.222125,112.076408,96.350997,103.612896
47,091 463 Reimarla,100.216510,92.222125,112.076408,96.350997,103.612896
48,091 464 Marttila,100.216510,92.222125,112.076408,96.350997,103.612896
49,091 465 Pitäjänmäen yritysalue,100.216510,92.222125,112.076408,96.350997,103.612896

## Merge one-person households and morbidity index with population dataframe

In [11]:
# Read population data (including district names with and without å, ä, ö)
population_df2 = pd.read_csv('../data/population_df2.csv')

# Change gender to categorical type
population_df2['Gender'] = population_df2['Gender'].astype('category')

population_df2

,Gender,Education % 15-24 years Second degree and special vocational training degree,Education % 15-24 years Lowest higher and lower university level,Education % 15-24 years Higher university degree and research training,Education % 15-24 years All levels of education,Education % 15-24 years Elementary or unknown,Education % 15-24 years Total graduates,Education % 25-44 years Second degree and special vocational training degree,Education % 25-44 years Lowest higher and lower university level,Education % 25-44 years Higher university degree and research training,...,Married couple and children,Unmarried couple without children,Unmarried couple and children,Father and children,Mother and children,municipality,code,name,Area no-dots,Area
0,0,0.059870,0.008553,0.000342,0.116319,0.047554,0.068765,0.105371,0.083134,0.157030,...,0.231140,0.248261,0.064205,0.021402,0.092563,91,10,Kruununhaka,091 10 Kruununhaka,091 10 Kruununhaka
1,1,0.079023,0.016667,0.000575,0.145402,0.049138,0.096264,0.074138,0.103736,0.157471,...,0.231140,0.248261,0.064205,0.021402,0.092563,91,10,Kruununhaka,091 10 Kruununhaka,091 10 Kruununhaka
2,0,0.058338,0.007025,0.000000,0.100794,0.035431,0.065363,0.168601,0.136225,0.140195,...,0.129346,0.413074,0.055633,0.013908,0.067455,91,101,Vilhonvuori,091 101 Vilhonvuori,091 101 Vilhonvuori
3,1,0.088615,0.018624,0.001502,0.143286,0.034545,0.108741,0.123160,0.141484,0.147792,...,0.129346,0.413074,0.055633,0.013908,0.067455,91,101,Vilhonvuori,091 101 Vilhonvuori,091 101 Vilhonvuori
4,0,0.056744,0.008216,0.000382,0.115017,0.049675,0.065342,0.107375,0.081582,0.138135,...,0.227415,0.243374,0.058991,0.021659,0.094329,91,101,Vironniemen peruspiiri,091 101 Vironniemen peruspiiri,091 101 Vironniemen peruspiiri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,1,0.046091,0.006647,0.000399,0.113049,0.059912,0.053136,0.101443,0.095361,0.100946,...,0.275851,0.172889,0.083733,0.022858,0.145590,91,997,Esikaupungit,091 997 Esikaupungit,091 997 Esikaupungit
364,0,0.068623,0.009455,0.000423,0.122246,0.043744,0.078502,0.148989,0.112253,0.144381,...,0.202834,0.311098,0.077402,0.018974,0.104751,91,998,Kantakaupunki,091 998 Kantakaupunki,091 998 Kantakaupunki
365,1,0.088223,0.017459,0.001057,0.147080,0.040342,0.106738,0.100800,0.129216,0.164055,...,0.202834,0.311098,0.077402,0.018974,0.104751,91,998,Kantakaupunki,091 998 Kantakaupunki,091 998 Kantakaupunki
366,0,0.039430,0.002767,0.000000,0.142225,0.100028,0.042197,0.148727,0.036386,0.039568,...,NaN,NaN,NaN,NaN,NaN,91,999,Muut,091 999 Muut,091 999 Muut
367,1,0.086763,0.011123,0.000000,0.212681,0.114794,0.097887,0.113459,0.066741,0.084538,...,NaN,NaN,NaN,NaN,NaN,91,999,Muut,091 999 Muut,091 999 Muut

In [22]:
# Merge one-person households with population data
population_df3 = pd.merge(left=population_df2, right=ones_portions, how='left', on=['Gender', 'Area'])

# Merge morbidity index 
population_df3 = pd.merge(left=population_df3, right=morb, how='left', on='Area')
# Replace filled morbidity data with NaN for areas where population is too few to be included
morb_cols = morb.columns.drop('Area')
for col in morb_cols:
    population_df3[col] = population_df3.apply(lambda x: np.nan if pd.isna(x['One-person hh, All ages, %']) 
                                               else x[col], axis=1)

population_df3

,Gender,Education % 15-24 years Second degree and special vocational training degree,Education % 15-24 years Lowest higher and lower university level,Education % 15-24 years Higher university degree and research training,Education % 15-24 years All levels of education,Education % 15-24 years Elementary or unknown,Education % 15-24 years Total graduates,Education % 25-44 years Second degree and special vocational training degree,Education % 25-44 years Lowest higher and lower university level,Education % 25-44 years Higher university degree and research training,...,"One-person hh, Age 65-69, %","One-person hh, Age 70-74, %","One-person hh, Age 75-79, %","One-person hh, Age 80-84, %","One-person hh, Age 85, %","Morbidity, Morbidity index","Morbidity, Mortality index","Morbidity, Disability pension index","Morbidity, Medicine reimbursement index","Morbidity, Chronic diseases index"
0,0,0.059870,0.008553,0.000342,0.116319,0.047554,0.068765,0.105371,0.083134,0.157030,...,0.011049,0.012533,0.008740,0.007091,0.003793,67.586539,69.787493,47.104700,85.867423,76.318461
1,1,0.079023,0.016667,0.000575,0.145402,0.049138,0.096264,0.074138,0.103736,0.157471,...,0.022977,0.025145,0.024277,0.019509,0.017341,67.586539,69.787493,47.104700,85.867423,76.318461
2,0,0.058338,0.007025,0.000000,0.100794,0.035431,0.065363,0.168601,0.136225,0.140195,...,0.015407,0.012552,0.008150,0.004640,0.003391,106.524701,108.962657,110.659740,99.951705,105.484865
3,1,0.088615,0.018624,0.001502,0.143286,0.034545,0.108741,0.123160,0.141484,0.147792,...,0.023286,0.024842,0.019840,0.014227,0.014227,106.524701,108.962657,110.659740,99.951705,105.484865
4,0,0.056744,0.008216,0.000382,0.115017,0.049675,0.065342,0.107375,0.081582,0.138135,...,0.011049,0.012533,0.008740,0.007091,0.003793,67.586539,69.787493,47.104700,85.867423,76.318461
5,1,0.069618,0.012837,0.000494,0.130184,0.047235,0.082949,0.070441,0.098255,0.145161,...,0.022977,0.025145,0.024277,0.019509,0.017341,67.586539,69.787493,47.104700,85.867423,76.318461
6,0,0.064842,0.009263,0.000421,0.111579,0.037053,0.074526,0.167158,0.135579,0.182316,...,0.015407,0.012552,0.008150,0.004640,0.003391,106.524701,108.962657,110.659740,99.951705,105.484865
7,1,0.089182,0.017449,0.003102,0.159752,0.050019,0.109732,0.107406,0.141915,0.182629,...,0.023286,0.024842,0.019840,0.014227,0.014227,106.524701,108.962657,110.659740,99.951705,105.484865
8,0,0.061803,0.010049,0.000603,0.116270,0.043815,0.072455,0.127625,0.089740,0.146116,...,0.011699,0.009661,0.007445,0.006204,0.005761,65.665101,73.060317,43.092436,80.842549,67.995023
9,1,0.081641,0.018190,0.001015,0.139086,0.038240,0.100846,0.094924,0.103130,0.165651,...,0.022764,0.023986,0.023680,0.016042,0.015278,65.665101,73.060317,43.092436,80.842549,67.995023
10,0,0.076042,0.013393,0.000664,0.136864,0.046765,0.090099,0.128397,0.102551,0.151973,...,0.008412,0.007656,0.007656,0.003261,0.003828,82.818148,74.817956,78.870986,94.765503,88.586840
11,1,0.089387,0.020824,0.001572,0.154118,0.042336,0.111782,0.097097,0.121016,0.162418,...,0.018949,0.022258,0.018605,0.013320,0.011902,82.818148,74.817956,78.870986,94.765503,88.586840
12,0,0.083077,0.009231,0.000000,0.139487,0.047179,0.092308,0.172308,0.123077,0.228718,...,0.015407,0.012552,0.008150,0.004640,0.003391,106.524701,108.962657,110.659740,99.951705,105.484865
13,1,0.067457,0.008204,0.002735,0.144941,0.066545,0.078396,0.131267,0.173200,0.221513,...,0.023286,0.024842,0.019840,0.014227,0.014227,106.524701,108.962657,110.659740,99.951705,105.484865
14,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,0,0.066711,0.007906,0.000165,0.114808,0.040026,0.074782,0.138857,0.106902,0.155493,...,0.014470,0.011286,0.009984,0.004486,0.006801,87.902482,95.685431,78.013245,90.008771,85.981219
17,1,0.093139,0.017841,0.000656,0.142857,0.031221,0.111636,0.087105,0.119507,0.174341,...,0.019924,0.027040,0.028107,0.020754,0.021466,87.902482,95.685431,78.013245,90.008771,85.981219
18,0,0.041327,0.005740,0.000522,0.094135,0.046546,0.047589,0.108328,0.106971,0.190357,...,0.012281,0.010551,0.007956,0.005016,0.005535,70.974337,72.153629,51.920147,88.849234,76.159888
19,1,0.046732,0.012298,0.000791,0.093904,0.034083,0.059821,0.067639,0.117094,0.205552,...,0.021396,0.027011,0.024583,0.019196,0.024962,70.974337,72.153629,51.920147,88.849234,76.159888
20,0,0.042033,0.007820,0.000000,0.079179,0.029326,0.049853,0.163245,0.131965,0.159335,...,0.015407,0.012552,0.008150,0.004640,0.003391,106.524701,108.962657,110.659740,99.951705,105.484865
21,1,0.076793,0.015190,0.001688,0.124051,0.030380,0.093671,0.101266,0.159494,0.169620,...,0.023286,0.024842,0.019840,0.014227,0.014227,106.524701,108.962657,110.659740,99.951705,105.484865
22,0,0.064103,0.007597,0.000237,0.096154,0.024217,0.071937,0.174027,0.122032,0.140788,...,0.015407,0.012552,0.008150,0.004640,0.003391,106.524701,108.962657,110.659740,99.951705,105.484865
23,1,0.107779,0.015863,0.000652,0.148414,0.024120,0.124294,0.129726,0.155150,0.175141,...,0.023286,0.024842,0.019840,0.014227,0.014227,106.524701,108.962657,110.659740,99.951705,105.484865
24,0,0.074593,0.008143,0.000977,0.104886,0.021173,0.083713,0.213355,0.135831,0.162541,...,0.015407,0.012552,0.008150,0.004640,0.003391,106.524701,108.962657,110.659740,99.951705,105.484865
25,1,0.136138,0.021034,0.000584,0.184925,0.027169,0.157756,0.139936,0.180543,0.192229,...,0.023286,0.024842,0.019840,0.014227,0.014227,106.524701,108.962657,110.659740,99.951705,105.484865
26,0,0.083382,0.008975,0.000290,0.118124,0.025478,0.092646,0.202953,0.136653,0.134627,...,0.024051,0.018350,0.010511,0.004454,0.004810,128.255733,134.511999,147.868406,102.386794,111.549133
27,1,0.140203,0.019707,0.000563,0.193412,0.032939,0.160473,0.137669,0.163288,0.170045,...,0.020746,0.024929,0.019575,0.014221,0.015560,128.255733,134.511999,147.868406,102.386794,111.549133
28,0,0.061654,0.004511,0.000501,0.084712,0.018045,0.066667,0.183960,0.157895,0.153885,...,0.024051,0.018350,0.010511,0.004454,0.004810,128.255733,134.511999,147.868406,102.386794,111.549133
29,1,0.092774,0.017249,0.001399,0.132867,0.021445,0.111422,0.135664,0.183683,0.211655,...,0.020746,0.024929,0.019575,0.014221,0.015560,128.255733,134.511999,147.868406,102.386794,111.549133
30,0,0.071214,0.011341,0.000500,0.129753,0.046698,0.083055,0.109406,0.085724,0.157605,...,0.008412,0.007656,0.007656,0.003261,0.003828,82.818148,74.817956,78.870986,94.765503,88.586840
31,1,0.088785,0.019966,0.002266,0.151232,0.040215,0.111017,0.073775,0.107760,0.167941,...,0.018949,0.022258,0.018605,0.013320,0.011902,82.818148,74.817956,78.870986,94.765503,88.586840
32,0,0.066711,0.007906,0.000165,0.114808,0.040026,0.074782,0.138857,0.106902,0.155493,...,0.014470,0.011286,0.009984,0.004486,0.006801,87.902482,95.685431,78.013245,90.008771,85.981219
33,1,0.093139,0.017841,0.000656,0.142857,0.031221,0.111636,0.087105,0.119507,0.174341,...,0.019924,0.027040,0.028107,0.020754,0.021466,87.902482,95.685431,78.013245,90.008771,85.981219
34,0,0.078893,0.012807,0.000000,0.131148,0.039447,0.091701,0.145492,0.115266,0.175717,...,0.014742,0.010471,0.008129,0.006613,0.005787,100.060517,87.922642,110.102059,102.156851,100.630765
35,1,0.109503,0.020727,0.001173,0.173641,0.042237,0.131404,0.088385,0.137270,0.185765,...,0.026495,0.027665,0.029155,0.022026,0.029049,100.060517,87.922642,110.102059,102.156851,100.630765
36,0,0.107273,0.005455,0.000000,0.157273,0.044545,0.112727,0.145455,0.094545,0.153636,...,0.014742,0.010471,0.008129,0.006613,0.005787,100.060517,87.922642,110.102059,102.156851,100.630765
37,1,0.104768,0.017461,0.000000,0.151108,0.028878,0.122230,0.087979,0.104097,0.147750,...,0.026495,0.027665,0.029155,0.022026,0.029049,100.060517,87.922642,110.102059,102.156851,100.630765
38,0,0.051262,0.002002,0.000400,0.140969,0.087305,0.053664,0.134161,0.077693,0.081298,...,0.014742,0.010471,0.008129,0.006613,0.005787,100.060517,87.922642,110.102059,102.156851,100.630765
39,1,0.039048,0.004271,0.000000,0.108908,0.065589,0.043319,0.081757,0.079927,0.083588,...,0.026495,0.027665,0.029155,0.022026,0.029049,100.060517,87.922642,110.102059,102.156851,100.630765
40,0,0.046646,0.009329,0.000444,0.109729,0.053310,0.056419,0.143492,0.126610,0.121279,...,0.009980,0.012475,0.009481,0.002994,0.003493,102.250403,109.181191,89.403210,108.166810,105.737299
41,1,0.053404,0.015795,0.000376,0.109816,0.040241,0.069575,0.092892,0.123355,0.136518,...,0.021759,0.024910,0.019808,0.015756,0.017557,102.250403,109.181191,89.403210,108.166810,105.737299
42,0,0.109920,0.005362,0.000000,0.171582,0.056300,0.115281,0.203753,0.190349,0.115281,...,0.009980,0.012475,0.009481,0.002994,0.003493,102.250403,109.181191,89.403210,108.166810,105.737299
43,1,0.177874,0.032538,0.002169,0.281996,0.069414,0.212581,0.121475,0.164859,0.143167,...,0.021759,0.024910,0.019808,0.015756,0.017557,102.250403,109.181191,89.403210,108.166810,105.737299
44,0,0.058646,0.006651,0.000000,0.120314,0.055018,0.065296,0.139057,0.115478,0.111850,...,0.009980,0.012475,0.009481,0.002994,0.003493,102.250403,109.181191,89.403210,108.166810,105.737299
45,1,0.061078,0.016168,0.000000,0.128743,0.051497,0.077246,0.098802,0.132934,0.114970,...,0.021759,0.024910,0.019808,0.015756,0.017557,102.250403,109.181191,89.403210,108.166810,105.737299
46,0,0.082278,0.012658,0.002110,0.118143,0.021097,0.097046,0.175105,0.185654,0.210970,...,0.009980,0.012475,0.009481,0.002994,0.003493,102.250403,109.181191,89.403210,108.166810,105.737299
47,1,0.153226,0.026210,0.002016,0.215726,0.034274,0.181452,0.149194,0.199597,0.183468,...,0.021759,0.024910,0.019808,0.015756,0.017557,102.250403,109.181191,89.403210,108.166810,105.737299
48,0,0.050068,0.008119,0.000000,0.079838,0.021651,0.058187,0.146143,0.125846,0.163735,...,0.014742,0.010471,0.008129,0.006613,0.005787,100.060517,87.922642,110.102059,102.156851,100.630765
49,1,0.079621,0.016114,0.001896,0.124171,0.026540,0.097630,0.090047,0.137441,0.153555,...,0.026495,0.027665,0.029155,0.022026,0.029049,100.060517,87.922642,110.102059,102.156851,100.630765

In [23]:
# Save to file population_df3.csv
population_df3.to_csv('../data/population_df3.csv', index=False)